### PR TITLE
updated the xcvr serial number to support hypen

### PR DESCRIPTION
**Pull request by vishnubraj**
updated the xcvr serial number to support hypen

### CODE REVIEW

**Comment by vishnubraj** [comment]
This closes https://github.com/networktocode/ntc-templates/issues/1707

**Comment by jvanderaa** [comment]
Can we add a test case with the hyphen on it?

**Comment by vishnubraj** [comment]
@jvanderaa  Added the test cases, Please check.

**Comment by vishnubraj** [comment]
@jvanderaa Can you please check this?

**Comment by jmcgill298** [comment]
Thanks @vishnubraj this has been resolved in https://github.com/networktocode/ntc-templates/pull/1721

**Pull request closed without merging**
