### PR TITLE
Jorlandobr

### PR DESCRIPTION
**Pull request by jmcgill298**

### CODE REVIEW

**Comment by jorlandobr** [comment]
@jmcgill298 ,

What question wasn't replied on #1615? I'm confused...

**Comment by jmcgill298** [comment]
https://github.com/networktocode/ntc-templates/pull/1615#discussion_r1577919225

https://github.com/networktocode/ntc-templates/pull/1615#discussion_r1578309774

**Comment by jorlandobr** [comment]
I replied both and added the test cases, as I staed in the response.

**Comment by jmcgill298** [comment]
Perhaps you did not submit the response, as I do not see any comments outside of my own, and I do not see an email with a response

**Comment by jorlandobr** [comment]
I don't have much experience with github, maybe the way I replied wasn't flagged as a response, but after your questions on apr/15 I renamed fields with "IFACE" to "INTERFACE" and added comments to explain the extra line for truncated values and test cases that showed the problem.

I add a print screen here from what I see on the comments.

**Comment by jorlandobr** [comment]
Screenshot_20240705-120216

**Comment by jmcgill298** [comment]
ya, that shows as pending, so only you can see that until you submit your review. I added a match to catch that line in this update

**Comment by jorlandobr** [comment]
As I said, I'm not experiencied in this! I thought that it was "you made alterations, that are pending review" not an alert that I shold submmit it. My bad! Submmited!

Thanks for the help!

**Review by jorlandobr — APPROVED** [review]

**Review by jorlandobr — APPROVED** [review]

**Review by jvanderaa — APPROVED** [review]

**Pull request merged**
