### PR TITLE
Enhancement - fortinet - get router info bgp summary

### PR DESCRIPTION
**Pull request by ccorvese**
##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
Name of template:  fortinet_get_router_info_bgp_summary.template
OS: fortinet
Command: get router info bgp summary

##### SUMMARY
Adds functionality to obtain BGP neighbour status on fortinet.

### CODE REVIEW

**Comment by jmcgill298** [comment]
@ccorvese is this for FortiGate?

**Comment by ccorvese** [comment]
@jmcgill298 yes, this is for a Fortinet firewall using fortiOS. Looks like it's failing in a couple of spots. One is index, and the other may be the name of the template in the index?

**Comment by jmcgill298** [comment]
okay, the platform should be changed to fortinet_fortios, and that would also need to be updated in [test_index_order#L64](https://github.com/networktocode/ntc-templates/blob/0ef73e4e79737d1222757141cd91605dddabf000/tests/test_index_order.py#L64)

**Comment by jmcgill298** [comment]
Still need to update the template name and test directory with `fortinet_fortios`

**Comment by jmcgill298** [comment]
need to delete the `tests/fortinet/` directory

**Comment by ccorvese** [comment]
Thanks for the guidance @jmcgill298 ! Still very new to git and programming. Looks like it's only failing on one check now.

**Comment by jmcgill298** [comment]
okay, in the index file, the platform is still just `fortinet` (this is the third column entry in the row). Also, the test file should nest the expected results under `parsed_sample`, like:
```yaml
---
parsed_sample:
  - key1: value1
    key2: value2
  - key1: value1
    key2: value2
```

Also, before pushing, you can run tox locally, you just need to have python3.6 installed on the machine, or update the `tox.ini` file to use a version of python available on the machine. If you make changes to the tox.ini file, then you would not want to commit those.

**Comment by jmcgill298** [comment]
Thanks @ccorvese

**Comment by ccorvese** [comment]
Thanks for your help @jmcgill298 I really appreciate it!

**Comment by jmcgill298** [comment]
you're welcome

**Pull request merged**
