### PR TITLE
Fix windows testrun

### PR DESCRIPTION
**Pull request by viktorkertesz**
##### ISSUE TYPE
 - Bugfix Pull Request

##### SUMMARY
Fixes pytest run on Windows. Reading template file logic is updated to be platform independent.

### CODE REVIEW

**Comment by jvanderaa** [comment]
Is there a particular bug that has this issue? I know that we have had developers running these tests on Windows for a long while now.

**Comment by jvanderaa** [comment]
@jmcgill298 probably a review for you.

**Comment by jmcgill298** [comment]
I believe this should be fixed

**Comment by jmcgill298** [comment]
believe to be fixed and not heard back, so closing as either fixed or stale

**Pull request closed without merging**
