### PR TITLE
feat(ubiquiti): add show ip route template

### PR DESCRIPTION
**Pull request by guillaume-mbali**
**ISSUE TYPE**
New Template Pull Request

**COMPONENT**
ubiquiti_edgerouter_show_ip_route.textfsm, edgerouter, show ip route

**SUMMARY**
Added the ubiquiti edgerouter template to show ip route

### CODE REVIEW

**Review by jmcgill298 — CHANGES_REQUESTED** [review]
Hi @guillaume-mbali, please see the comments from https://github.com/networktocode/ntc-templates/pull/1274 as they apply to this PR too. Overall it looks good, just a couple of things to button up.

**Comment by guillaume-mbali** [comment]
Hi @jmcgill298, I have also made the changes from the comment https://github.com/networktocode/ntc-templates/pull/1274  in this PR. Thanks you.

**Comment by jmcgill298** [comment]
> Hi @jmcgill298, I have also made the changes from the comment #1274 in this PR. Thanks you.

I don't see the changes in this PR

**Comment by guillaume-mbali** [comment]
Hi @jmcgill298, normally the PR is updated with the changes.

**Review by jmcgill298 — APPROVED** [review]

**Pull request merged**
