### PR TITLE
Update cisco_asa_ping.textfsm

### PR DESCRIPTION
**Pull request by jorlandobr**
Added U and Q response to RESPONSE STREAM

Cisco has four valid outputs for ping: . (fail) ! (success) U (unreachable) Q (quench)

U and Q were missing. Testing an output that carried these values would generate an error.

### CODE REVIEW

**Comment by jvanderaa** [comment]
Can you add additional test cases?

**Comment by jorlandobr** [comment]
Added test cases (yml and raw fles) in jorlandobr-patch-1

**Comment by jvanderaa** [comment]
Looks great @jorlandobr! Thank you for the contribution.

**Comment by jvanderaa** [comment]
I hope to have a new release out next week that will incorporate this.

**Pull request merged**
