### PR TITLE
Fix typos and issues in fortinet_get_system_status for FortiGate 7.2 VM

### PR DESCRIPTION
**Pull request by glennake**

### CODE REVIEW

**Review by jmcgill298 — CHANGES_REQUESTED** [review]
Thanks for the PR @glennake 

For updates to existing templates, the test data for those templates will need to be updated to reflect the changes.

For new templates, we require test cases be included in the PR, and we now require that every state provide a final line `^. -> Error` to ensure that we are capturing the data.

**Comment by mjbear** [comment]
> Thanks for the PR @glennake
> 
> For updates to existing templates, the test data for those templates will need to be updated to reflect the changes.

https://github.com/networktocode/ntc-templates/blob/master/docs/dev/dev_parser.md#development-helper-scripts

> 
> For new templates, we require test cases be included in the PR, 

https://github.com/networktocode/ntc-templates/blob/master/docs/dev/dev_parser.md#tests
https://github.com/networktocode/ntc-templates/blob/master/docs/user/faq.md#i-simply-want-to-add-my-template-to-the-project-i-do-not-want-to-add-all-of-these-tests-and-controls-can-i-just-do-so

> and we now require that every state provide a final line `^. -> Error` to ensure that we are capturing the data.

https://github.com/networktocode/ntc-templates/blob/master/docs/user/faq.md#why-is-there-a-requirement-to-use-error-in-every-template

Hopefully the above hyperlinks to documentation helps.
:dart: There isn't much effort left from you @glennake to complete the requirements so this pull request (PR) could be reviewed and merged in!

**Comment by jmcgill298** [comment]
@glennake are you still interested in seeing this PR completed?

**Comment by mjbear** [comment]
@pnpestov
Might you be willing to contribute test data (raw command output) so I can help close this?

* fortinet_get_system_status
* fortinet_get_router_info_ospf_neighbor

**Comment by mjbear** [comment]
resolved by #1873

**Pull request closed without merging**
