### PR TITLE
Create cisco_ios_show_license_status.textfsm

### PR DESCRIPTION
**Pull request by travisjohnsonga**
Create file for basics of show license status for smart licensing

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT
cisco_ios_show_license_status

##### SUMMARY
New template for command.  When using smart licensing, this will ease the check to see if the device is registered, and the status of registration

```
Smart Licensing is ENABLED

Utility:
  Status: DISABLED

Data Privacy:
  Sending Hostname: yes
    Callhome hostname privacy: DISABLED
    Smart Licensing hostname privacy: DISABLED
  Version privacy: DISABLED

Transport:
  Type: Callhome

Registration:
  Status: REGISTERED
  Smart Account: My Company Name
  Virtual Account: actname
  Export-Controlled Functionality: ALLOWED
  Initial Registration: SUCCEEDED on Aug 22 18:58:03 2022 UTC
  Last Renewal Attempt: None
  Next Renewal Attempt: Feb 18 18:58:03 2023 UTC
  Registration Expires: Aug 22 18:52:49 2023 UTC

License Authorization: 
  Status: OUT OF COMPLIANCE on Aug 22 18:58:17 2022 UTC
  Last Communication Attempt: SUCCEEDED on Aug 22 18:58:17 2022 UTC
  Next Communication Attempt: Aug 23 06:58:17 2022 UTC
  Communication Deadline: Nov 20 18:53:16 2022 UTC

Export Authorization Key:
  Features Authorized:
    <none>
```

### CODE REVIEW

**Comment by jvanderaa** [comment]
It's been a while. I can get these updates in, but need some example output.

**Comment by jvanderaa** [comment]
@travisjohnsonga would you happen to have an output that we can add in to help build tests.

**Comment by ryanmerolle** [comment]
What is required to push this through. I'd be happy to help

**Comment by jmcgill298** [comment]
@travisjohnsonga @ryanmerolle as requested, we need a test case to merge. Additionally, the template does not follow standards of ending each State with a catchall `. -> Error`

**Comment by mjbear** [comment]
Since this is from August 2022, there's going to be big time rebasing and merge conflict resolution required.
I think I heard @ryanmerolle say he can take the merge pain though (just kidding). :laughing: 

> @travisjohnsonga would you happen to have an output that we can add in to help build tests.

@jvanderaa
The code block at the top (with SL enabled) seems right when I compare it to output I have for a device with Smart Licensing **_disabled_**. The disabled output is probably still worth putting in the test cases, but it's not nearly as important as the **enabled** Smart Licensing output! :grinning: 

> What is required to push this through. I'd be happy to help

@ryanmerolle
:question: Might you have access to a Cisco IOS device that has Smart Licensing **enabled**?

:fire: Ah, ha! I found [some example output for 8300 and 4000 platforms (thank you Cisco docs)](https://www.cisco.com/c/en/us/td/docs/routers/sl_using_policy/b-sl-using-policy/cmd_ref.html#Cisco_Command_Page.dita_537ade59-8329-491a-b200-7ec99a8aeb04__example_zsr_plm_nnb), woohoo!
:arrow_right: Though it can't hurt to get actual live output from a device with Smart Licensing enabled.

**Comment by mjbear** [comment]
> Since this is from August 2022, there's going to be big time rebasing and merge conflict resolution required. I think I heard @ryanmerolle say he can take the merge pain though (just kidding). 😆

The merge conflicts are horrible.
(ex: the index moved along with so many other template changes)

This PR doesn't even have test data so it doesn't seem worth saving the commit history for the gauntlet of merge conflicts.

_Unless Travis responds back, updates his master branch to latest, and create a feature branch (which others of us can pull commits from to add our test data) ..._
then I'm going to spin up a new branch a mention to @travisjohnsonga's PR/fork will have to do.

**Comment by mjbear** [comment]
:bulb: I have a template worked up, but will need more test data.

Travis' output (in this thread) and output from a device with Smart Licensing disabled have some syntax/section differences. Raw output from a device running a _newer IOS/IOS-XE version would be highly encouraged_.

If @ryanmerolle wants to collaborate I'll push my branch to my GH fork so he can pull and work with the template.

**Comment by ChristopherJHart** [comment]
Below is sample output from a real device (ISR4451-X, IOS-XE 17.12.4) with Smart Licensing Using Policy configured and registered.
```
Router#show license status  
Utility:
  Status: DISABLED

Smart Licensing Using Policy:
  Status: ENABLED

Account Information:
  Smart Account: Sample Smart Account As of Aug 03 09:03:25 2024 est
  Virtual Account: DEFAULT

Data Privacy:
  Sending Hostname: yes
    Callhome hostname privacy: DISABLED
    Smart Licensing hostname privacy: DISABLED
  Version privacy: DISABLED

Transport:
  Type: Smart
  URL: https://smartreceiver.cisco.com/licservice/license
  Proxy:
    Address: proxy.foo.bar.com
    Port: 80
    Username: <empty>
    Password: <empty>
  VRF: <empty>

Policy:
  Policy in use: Merged from multiple sources.
  Reporting ACK required: yes (CISCO default)
  Unenforced/Non-Export Perpetual Attributes:
    First report requirement (days): 365 (CISCO default)
    Reporting frequency (days): 0 (CISCO default)
    Report on change (days): 90 (CISCO default)
  Unenforced/Non-Export Subscription Attributes:
    First report requirement (days): 90 (CISCO default)
    Reporting frequency (days): 90 (CISCO default)
    Report on change (days): 90 (CISCO default)
  Enforced (Perpetual/Subscription) License Attributes:
    First report requirement (days): 0 (CISCO default)
    Reporting frequency (days): 0 (CISCO default)
    Report on change (days): 0 (CISCO default)
  Export (Perpetual/Subscription) License Attributes:
    First report requirement (days): 0 (CISCO default)
    Reporting frequency (days): 0 (CISCO default)
    Report on change (days): 0 (CISCO default)

Miscellaneous:
  Custom Id: <empty>

Usage Reporting:
  Last ACK received: Aug 03 09:03:25 2024 est
  Next ACK deadline: Aug 03 09:03:25 2025 est
  Reporting push interval: 0 (no reporting)
  Next ACK push check: Aug 03 09:05:29 2024 est
  Next report push: <none>
  Last report push: Aug 03 09:03:26 2024 est
  Last report file write: <none>

Trust Code Installed: Aug 03 09:02:50 2024 est
 
Device Telemetry Report Summary:
================================
Data Channel: AVAILABLE
Reports on disk: 0 
```

**Comment by mjbear** [comment]
> Below is sample output from a real device (ISR4451-X, IOS-XE 17.12.4) with Smart Licensing Using Policy configured and registered.

Thank you @ChristopherJHart!

You might not have an opinion, but I'll ask ...
Is there anything else that might be useful to capture from the output (see below)?

```
---
parsed_sample:
  - sl_enabled: "ENABLED"
    sl_license_auth: ""
    sl_proxy_address: "proxy.foo.bar.com"
    sl_proxy_password: "<empty>"
    sl_proxy_port: "80"
    sl_proxy_username: "<empty>"
    sl_reg_status: ""
    sl_smart_acct: "Sample Smart Account"
    sl_transport: "Smart"
    sl_url: "https://smartreceiver.cisco.com/licservice/license"
    sl_virt_acct: "DEFAULT"
    sl_vrf: "<empty>"
```

**Comment by ChristopherJHart** [comment]
@mjbear In my opinion, the fields under the `Usage Reporting:` section could be useful to capture as well. I can see a use case where somebody writes automation validating recent connectivity between a device and CSSM, and in that use case, the Usage Reporting statistics would be very helpful.

**Comment by mjbear** [comment]
I submitted PR #1803

**Pull request closed without merging**
