### PR TITLE
Fix IOS interface link template uptime issue

### PR DESCRIPTION
**Pull request by paulbauer1**
Corrected issue with template not displaying uptime values correctly when there are hours in the uptime value. Added optional hours to the uptime regex statement.

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Can you add tests as well? 

We follow a simple mock and verify value setup, you can see a recent example here: https://github.com/networktocode/ntc-templates/pull/1841/files and documentation of the process here: https://ntc-templates.readthedocs.io/en/latest/dev/dev_parser/#tests


Essentially we are looking for new output that shows your new condition, while ensuring that there is no regressions to other conditions. This also protects your update in the future, in case someone were to inadvertently revert your change.

**Comment by paulbauer1** [comment]
I added a new test file, tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link4.raw. It is basically the same as the existing first raw file just with a newly generated yaml file to go with it. The existing test file (tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link.raw) already contained the necessary data to validate my changes. Although, now the existing raw and yaml files fail testing as the bug I fixed had created bad data in the yaml file so that now fails. The tests/cisco_ios/show_interface_link/cisco_ios_show_interface_link.yaml file is no longer a valid yaml file now that the bug has been resolved.  Should I close this PR and create a new one in order to get the new test files incorporated and what should be done with the existing test files that now fail? Thank you.

**Comment by jmcgill298** [comment]
@paulbauer1 if the existing test cases are already symptomatic of the problem, then you just need to update the existing test cases with the correct values, and do not need to create a new test case

**Comment by paulbauer1** [comment]
I regenerated the cisco_ios_show_interface_link.yaml file. The other files were fine. All tests passed. 

============================================================================================== 2340 passed in 16.03s ==============================================================================================
All tests have passed!

**Review by jmcgill298 — CHANGES_REQUESTED** [review]
I created a PR back to you to fix the downtime not getting captured https://github.com/paulbauer1/ntc-templates/pull/1

**Review by jmcgill298 — APPROVED** [review]

**Comment by jmcgill298** [comment]
thanks @paulbauer1

**Pull request merged**
