### PR TITLE
Fix aruba aoscx lldp issue1453

### PR DESCRIPTION
**Pull request by mjbear**
Not caused by #1469 as that PR had not been merged when issue #1453 came in. :sweat_smile: 
Based off of #1469 and its modified capture group names so this PR should be merged last.

**Update 2024/06/21:**
Breaking change since the CDP/LLDP discovery protocol normalization shows up in this PR.
There's the real chance that #1469 may render this PR unnecessary. I'll rebase and find out. :grinning:

### CODE REVIEW

**Comment by mjbear** [comment]
The troubleshooting on issue #1453 continues, there may be more changes necessary before this gets merged in.

Thank you for holding off merging this PR.

**Comment by mjbear** [comment]
Ongoing troubleshooting. Hoping to determine today (9/8) if further changes are needed.
Thank you for holding off the merge of this PR. Much appreciated!

**Comment by mjbear** [comment]
It appears that PR #1559 put in some of the fixes for Aruba's System/Chassis syntax change.
This PR still has some value in consolidating the match lines and the capture group normalization.

**Comment by mjbear** [comment]
fixing a bunch of merge conflicts :nauseated_face: 
(since this is based off of another PR that hasn't been merged yet)

**Comment by mjbear** [comment]
'lotta merge conflict resolution on this rebase ... thankfully done

**Review by jmcgill298 — APPROVED** [review]

**Pull request merged**
