### PR TITLE
Adding support for avaya_ers show mlt command

### PR DESCRIPTION
**Pull request by kadecole**
##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
avaya_ers_show_mlt.template

##### SUMMARY
Adding support for avaya_ers `show mlt` command

```
                                                                        LACP
Id Name             Members                Bpdu   Mode  Status   Type   Key
-- ---------------- ---------------------- ------ ----- -------- ------ ----
1  UPLINK           49-50                  All    B     Disabled        NONE
2  Trunk #2         NONE                   All    B     Disabled        NONE
3  Trunk #3         NONE                   All    B     Disabled        NONE
4  Trunk #4         NONE                   All    B     Disabled        NONE
5  Trunk #5         NONE                   All    B     Disabled        NONE
6  Trunk #6         NONE                   All    B     Disabled        NONE
7  Trunk #7         NONE                   All    B     Disabled        NONE
8  Trunk #8         NONE                   All    B     Disabled        NONE
9  Trunk #9         NONE                   All    B     Disabled        NONE
10 Trunk #10        NONE                   All    B     Disabled        NONE
11 Trunk #11        NONE                   All    B     Disabled        NONE
12 Trunk #12        NONE                   All    B     Disabled        NONE
13 Trunk #13        NONE                   All    B     Disabled        NONE
14 Trunk #14        NONE                   All    B     Disabled        NONE
15 Trunk #15        NONE                   All    B     Disabled        NONE
16 Trunk #16        NONE                   All    B     Disabled        NONE
17 Trunk #17        NONE                   All    B     Disabled        NONE
18 Trunk #18        NONE                   All    B     Disabled        NONE
19 Trunk #19        NONE                   All    B     Disabled        NONE
20 Trunk #20        NONE                   All    B     Disabled        NONE
21 Trunk #21        NONE                   All    B     Disabled        NONE
22 Trunk #22        NONE                   All    B     Disabled        NONE
23 Trunk #23        NONE                   All    B     Disabled        NONE
24 Trunk #24        NONE                   All    B     Disabled        NONE
25 Trunk #25        NONE                   All    B     Disabled        NONE
26 Trunk #26        NONE                   All    B     Disabled        NONE
27 Trunk #27        NONE                   All    B     Disabled        NONE
28 Trunk #28        NONE                   All    B     Disabled        NONE
29 Trunk #29        NONE                   All    B     Disabled        NONE
30 Trunk #30        NONE                   All    B     Disabled        NONE
31 Trunk #31        NONE                   All    B     Disabled        NONE
32 Trunk #32        NONE                   All    B     Disabled        NONE
MODE Legend:
B=Basic, A=Advance, Man=ManLag, Dyn=DynLag
```

### CODE REVIEW

**Comment by kadecole** [comment]
I want to thank @jmcgill298 for help with this PR.

**Comment by jmcgill298** [comment]
```
IDNAME (.*?)
+Value MLTACTIVEMEMBERS (\S+?)
+Value MLTINACTIVEMEMBERS (\S+?)
+Value MLTBPDU (\S+?)
+Value MLTMODE (\S+?)
+Value MLTSTATUS (Enabled|Disabled)
+Value MLTTYPE (Access|Trunk|)
+Value MLTLACPKEY (\S+|)

**Comment by jmcgill298** [comment]
@kadecole any thoughts on my suggestion?

**Comment by kadecole** [comment]
Sorry missed your comment. I would hate to have overlap with other Variable names. As this is only for MLT information I thought it would be best to distinguish the variables with the MLT option. I am fine with changing to using underscores in the names.

**Comment by jmcgill298** [comment]
@kadecole not sure why you would need `MLT` to distinguish the names? All data being parsed by this would be namespaced already. Using the same key names across all platforms makes it easier/consistent to use the data in multi-platform environments.

@itdependsnetworks what do you think?

**Pull request merged**
