### PR TITLE
Normalize instances of NEIGHBOR_ID to ROUTER_ID

### PR DESCRIPTION
**Pull request by mjbear**
Standardization/normalization of NEIGHBOR_ID instances to ROUTER_ID
Breaking change on account of the capture group changes

- replace (several instances of) NEIGHBOR_ID with ROUTER_ID (as the latter appears more often and represent the same thing)

Note: There are some instances of NEIGHBOR_ID in templates that will remain (hp_procurve_show_cdp_neighbor and vmware_nsxv_show_ip_bgp_neighbor).

### CODE REVIEW

**Comment by mjbear** [comment]
working to rebase and resolve merge conflicts

**Comment by mjbear** [comment]
> Going to come back and check on this one again. I see ROUTER_ID and NEIGHBOR_ID as two separate things. NEIGHBOR_ID being that of router B from router A's perspective. I need to look at the raw output that are provided as examples. I'm guessing that we will be fine, I just need a bit more of a deeper look.

I'm going through raw test examples to confirm I didn't categorize anything incorrectly. So far neighbor ID has been the router ID and there's also an IP address capture group too (sometimes they match if the RID isn't manually set or the conditions for dynamic RID selection happen to choose that interface).

I've found a few items I'm going to modify.

**Comment by jvanderaa** [comment]
Let's talk through this one a little bit for me. This is the example from `cisco_xr_show_ospf_vrf_all_neighbor`. 

```

Wed Jul 27 17:18:33.921 CST

* Indicates MADJ interface
# Indicates Neighbor awaiting BFD session up

Neighbors for OSPF 1, VRF red

Neighbor ID     Pri   State           Dead Time   Address         Interface
192.0.2.1       0     FULL/  -        00:00:39    192.0.2.2       Bundle-Ether10.10
    Neighbor is up for 5w0d
192.0.2.3       1     FULL/DR         00:00:39    192.0.2.4       TenGigE0/0/0/10.10
    Neighbor is up for 35w1d

Total neighbor count: 2


* Indicates MADJ interface
# Indicates Neighbor awaiting BFD session up

Neighbors for OSPF 1, VRF green

Neighbor ID     Pri   State           Dead Time   Address         Interface
192.0.2.5       0     FULL/  -        00:00:34    192.0.2.6       Bundle-Ether10.20
    Neighbor is up for 6d16h
192.0.2.7       1     FULL/DR         00:00:38    192.0.2.8       TenGigE0/0/0/10.20
    Neighbor is up for 35w1d

Total neighbor count: 2


* Indicates MADJ interface
# Indicates Neighbor awaiting BFD session up

Neighbors for OSPF 1, VRF blue

Neighbor ID     Pri   State           Dead Time   Address         Interface
192.0.2.9       1     FULL/BDR        00:00:39    192.0.2.10      Bundle-Ether10.30
    Neighbor is up for 35w1d
192.0.2.11      1     FULL/BDR        00:00:39    192.0.2.12      GigabitEthernet100/0/0/0
    Neighbor is up for 35w1d

Total neighbor count: 2
```

I think we do want this one as Neighbor ID wouldn't we? Or are we thinking it is the `ROUTER_ID` of the neighbor? 

For me when I'm thinking of OSPF, BGP and such with `ROUTER_ID` I'm thinking that is local to the box and `NEIGHBOR_ID` is the router ID of the neighboring device.

**Comment by mjbear** [comment]
> For me when I'm thinking of OSPF, BGP and such with `ROUTER_ID` I'm thinking that is local to the box and `NEIGHBOR_ID` is the router ID of the neighboring device.

@jvanderaa
I agree - `ROUTER_ID` should be used for local.
Unfortunately I didn't notice my flawed logic before putting in this PR (would have saved me some face :man_shrugging: ).

This entire PR should be ignored.
Thank you for catching it and apologies for eating up some extra cycles with it.

**Pull request closed without merging**
