### PR TITLE
adding cisco_xr_show_ip_bgp_summary.template

### PR DESCRIPTION
**Pull request by Sandeepsr**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

adding cisco_xr_show_ip_bgp_summary.template

##### SUMMARY

adding cisco_xr_show_ip_bgp_summary.template

```

```

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Can you take a look at: https://github.com/networktocode/ntc-templates/pull/167 and follow same recommendations?

**Comment by itdependsnetworks** [comment]
Take a look again at that other PR, it should end with 
``` 
  ^\s+$$
  ^$$
  ^.* -> Error "LINE NOT FOUND"
```

**Comment by Sandeepsr** [comment]
@itdependsnetworks , I tried that as well. it give me error :  Error: "LINE NOT FOUND". Line: 18.

**Comment by Sandeepsr** [comment]
@itdependsnetworks , okay I have fixed that, please review now

**Comment by itdependsnetworks** [comment]
Great, one last thing. Can you make state_prf... as just \S+ as that already contains \d+ within it

**Comment by Sandeepsr** [comment]
@itdependsnetworks , done

**Pull request merged**
