### PR TITLE
BugFix: Ciena Saos: Added more use cases to vlan_show

### PR DESCRIPTION
**Pull request by FragmentedPacket**
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT

ciena_saos_vlan_show.textfsm
##### SUMMARY
Adds in more use cases from #640 

@georgesnow @friday963

The name does change in these, is that OK?

### CODE REVIEW

**Comment by georgesnow** [comment]
Is this change you are referring to:

`Value VLAN_NAME ([0-9a-zA-Z_#]+)`

` Value NAME ([0-9a-zA-Z_#]+)`

**Comment by FragmentedPacket** [comment]
Correct. That is a difference between both of y'all templates and is disruptive for you

**Comment by georgesnow** [comment]
shouldn't effect me. I am not actually using the template for anything. I only added as baseline to basic output of the command.

**Comment by FragmentedPacket** [comment]
@georgesnow Thanks for the quick response!

**Pull request merged**
