### PR TITLE
Cisco ASA Show Logging Template

### PR DESCRIPTION
**Pull request by afoster213**
##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
cisco_asa_show_logging, cisco asa, show logging

##### SUMMARY
Parses show logging output from Cisco ASAs.  Follows the standard set up on the Cisco IOS show logging template.

### CODE REVIEW

**Comment by jmcgill298** [comment]
@afoster213 shouldn't this look more like #554 with different options depending on timestamp format?

**Comment by afoster213** [comment]
The ASA doesn't have the option to add a syslog number or timezone.  Only options I'm seeing across my examples are with and without hostname.  Happy to add in additional cases if anyone has any additional examples.

**Comment by afoster213** [comment]
@jmcgill298 I added another case for logs with no timestamps.  I'm not able to find any other cases though based on Cisco's documentation.  Here's the guide that I'm working off of.
https://www.cisco.com/c/en/us/support/docs/security/pix-500-series-security-appliances/63884-config-asa-00.html

**Comment by jmcgill298** [comment]
This should still account for multiline messages using Continue.Record on new messages and then capturing the message contents on subsequent match lines.

**Comment by afoster213** [comment]
@jmcgill298 Updated for multiline cases.

**Pull request merged**
