### PR TITLE
Added Avaya ERS templates

### PR DESCRIPTION
**Pull request by OfWolfAndMan**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

- Avaya ERS "Show vlan"
  * Provided information:
    [+] VLAN Identifier
    [+] VLAN Name
    [+] Active/Inactive
    [+] Interfaces associated
- Avaya ERS "Show sys-info" (Show version command for Avaya)
  * Provided information:
    [+] License
    [+] Base MAC address
    [+] Model
    [+] Serial Number
    [+] Switch Version
- Avaya ERS "Show mac-address-table"
  * Provided information:
    [+] Port
    [+] Mac Address
    [+] Type
    [+] VLAN
- Avaya ERS "Show interface name"
  * Provided information:
    [+] Port
    [+] Name
##### SUMMARY

Initial attempts at providing parsing abilities for the Avaya ERS switching
platform.

```

```

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Hi, thanks for the PR!!

Will try and take a look this weekend.

**Comment by OfWolfAndMan** [comment]
Thanks. I was also going to squeeze in some commands for Cumulus as well. Should have a few before the weekend.

**Comment by kadecole** [comment]
Looks like we are working on the same thing #155. I think we should work together on this. Maybe merge this request before mine.

**Comment by OfWolfAndMan** [comment]
@kadecole yeah I was trying to do the show_vlan_port_verbose command as well but using TextFSM, I couldn't figure out a feasible way to approach it based on the structure of the VLAN ID column. Not sure if there were any others you were working on.

**Comment by itdependsnetworks** [comment]
Thanks @OfWolfAndMan

**Pull request merged**
