### PR TITLE
Ciena standardprofile

### PR DESCRIPTION
**Pull request by georgesnow**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT
traffic-profile standard-profile show

##### SUMMARY
new template

### CODE REVIEW

**Comment by FragmentedPacket** [comment]
Bump.. Did you get hit by a bus? :P

**Comment by georgesnow** [comment]
ran out of time to work on this. I believe the issue I was having is the tests pass locally for me, but fail on travis. I might just drop this request. not sure when I will get a chance to pick it back up again.

**Comment by itdependsnetworks** [comment]
understood. will close in a week if no response.

**Comment by georgesnow** [comment]
I have some time again. I will review and see if I can get this working.

**Comment by georgesnow** [comment]
closing this one and creatinga new one

**Pull request closed without merging**
