### PR TITLE
Cisco WLC Command - Show 802 11a|b

### PR DESCRIPTION
**Pull request by timjsmith24**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

cisco_wlc_ssh_show_802_11b.template, .*, cisco_wlc_ssh, show 802.11b

##### SUMMARY

```

```

### CODE REVIEW

**Comment by jmcgill298** [comment]
What do you think of converting repetitive fields into lists? Example:
```yaml
parsed_sample:
- ac_support: Enabled
  beacon_interval: '100'
  data_rate: ["12m", "18m", "24m", "36m", "48m", "54m", "6m", "9m"]
  data_rate_value: ["Mandatory", "Supported", "Mandatory", " Supported", "Supported", "Supported", "Mandatory", "Supported"]
  edca: default-wmm
  max_client: '200'
  mcs_rate: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"]
  mcs_rate_value: ["Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported", "Supported"]
  n_support: Enabled
  rssi_low_check: Disabled
  rssi_thres: '-80'
  status: Disabled
  video_amc: Disabled
  video_cac_method: Static
  video_max_bandwidth: '0'
  video_roaming_bandwidth: '0'
  voice_amc: Disabled
  voice_cac_method: Load-Based
  voice_max_bandwidth: '75'
  voice_roaming_bandwidth: '6'
```

**Comment by timjsmith24** [comment]
I had thought about that, but having them as key:values is helpful when trying to identify which data rates/mcs rates are set to a specific value. Instead of looking up the list index for the value then the using that index in the list of rates. This was the only way I could figure out setting them as key:values.

**Comment by jmcgill298** [comment]
We generally post-process TextFSM output, and this would be part of that process. Here is an example of post-processing two corresponding lists.

```python
>>> parsed_sample = [
        {
            'data_rate': ['12m', '18m', '24m', '36m', '48m', '54m', '6m', '9m'],
            'data_rate_value': ['Mandatory', 'Supported', 'Mandatory', ' Supported', 'Supported', 'Supported', 'Mandatory', 'Supported'],
        }
    ]
>>> command_data = parsed_sample[0]
>>> data_rate = command_data["data_rate"]
>>> data_rate_value = command_data["data_rate_value"]
>>> post_processed = {"data_rates": dict(zip(data_rate, data_rate_value))}
>>> post_processed
{
    'data_rates': {
        '12m': 'Mandatory',
        '18m': 'Supported',
        '24m': 'Mandatory',
        '36m': ' Supported',
        '48m': 'Supported',
        '54m': 'Supported',
        '6m': 'Mandatory',
        '9m': 'Supported'
    }
}
>>> 
```

**Comment by timjsmith24** [comment]
Ok so I made lists out of the data rates, mcs rates, and the support specs. This also allowed me to combine the 802.11a and 802.11b commands

**Comment by jmcgill298** [comment]
@timjsmith24 The command for the index file should escape the `.`, as this is a regex line so it reads as anything instead of as a literal `.`. I made this update and that caused an issue with the test files properly testing. I updated the test files and that is working properly. In addition, we require that that each state end with `^. -> Error` to ensure each line in the data is accounted for, which gives us confidence that we are accurately parsing the command output. I have also added these to the template, and the tests still pass.

However, I went to make a PR back into your branch, but GitHub is not letting me issue PRs to your fork. Can you check my `show_802_11b` branch? If you are good with those changes, can you pull them into your branch? Please let me know if you have any questions, or any issues with the changes on my branch.

**Comment by timjsmith24** [comment]
looks good. Thanks!

**Pull request merged**
