### PR TITLE
Add cisco show power inline

### PR DESCRIPTION
**Pull request by Tes3awy**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

`cisco_ios_show_power_inline.textfsm`, Cisco IOS, show power inline

##### SUMMARY

```
Interface Admin  Oper       Power   Device              Class Max
                            (Watts)                            
--------- ------ ---------- ------- ------------------- ----- ----
Gi1/3     auto   on         15.4    Ieee PD             3     30.0 
Gi1/4     auto   off        0.0     n/a                 n/a   30.0 
Gi1/5     auto   on         15.4    Ieee PD             3     30.0 
Gi1/6     auto   on         30.0    Ieee PD             4     30.0 
Gi1/7     auto   off        0.0     n/a                 n/a   30.0 
Gi1/8     auto   off        0.0     n/a                 n/a   30.0 
Gi1/9     auto   on         15.4    Ieee PD             3     30.0 
Gi1/10    auto   off        0.0     n/a                 n/a   30.0 
```

### CODE REVIEW

**Comment by jvanderaa** [comment]
Is this the complete output of the command? On my C3750 I have an additional "table" that would need to be captured as well. Or at least accounted for in some fashion.

```
joshv-sw01# show power inline

Module   Available     Used     Remaining
          (Watts)     (Watts)    (Watts)
------   ---------   --------   ---------
1           370.0       30.8       339.2
Interface Admin  Oper       Power   Device              Class Max
                            (Watts)
--------- ------ ---------- ------- ------------------- ----- ----
Gi1/0/1   auto   off        0.0     n/a                 n/a   15.4
Gi1/0/2   auto   off        0.0     n/a                 n/a   15.4
Gi1/0/3   auto   off        0.0     n/a                 n/a   15.4
Gi1/0/4   auto   off        0.0     n/a                 n/a   15.4
```

**Comment by Tes3awy** [comment]
> Is this the complete output of the command? On my C3750 I have an additional "table" that would need to be captured as well. Or at least accounted for in some fashion.
> 
> 
> 
> ```
> 
> joshv-sw01# show power inline
> 
> 
> 
> Module   Available     Used     Remaining
> 
>           (Watts)     (Watts)    (Watts)
> 
> ------   ---------   --------   ---------
> 
> 1           370.0       30.8       339.2
> 
> Interface Admin  Oper       Power   Device              Class Max
> 
>                             (Watts)
> 
> --------- ------ ---------- ------- ------------------- ----- ----
> 
> Gi1/0/1   auto   off        0.0     n/a                 n/a   15.4
> 
> Gi1/0/2   auto   off        0.0     n/a                 n/a   15.4
> 
> Gi1/0/3   auto   off        0.0     n/a                 n/a   15.4
> 
> Gi1/0/4   auto   off        0.0     n/a                 n/a   15.4
> 
> ```

Yeah, this is the complete output from the switch. Mine is from an IE3200 switch. Can you please help me in what I should do next?

**Comment by jvanderaa** [comment]
We will need to get the parsed examples in place. I will see if I can add to this PR or not for that. Then an update for the other device types.

**Comment by jvanderaa** [comment]
We will not need to get every device type out there. Just the ones that can be addressed. I should have an update of the plan for that tomorrow yet.

**Comment by jvanderaa** [comment]
We will get this merged in, but not for a complete release. I will then try to make some updates to it.

**Comment by Tes3awy** [comment]
> We will get this merged in, but not for a complete release. I will then try to make some updates to it.

Sure @jvanderaa. This is my first contribution to the repo and it might be not that good. I'll keep on reading and learning for future contributions. Thank you

**Comment by jvanderaa** [comment]
In the end the show command on some of the IOS devices has really two outputs. One of the overall power status for each device (and multiple when in a stack, so we will need some stack output to get done right as well). Then it has each individual interface's power status.

The one output that you have includes the interface status only. So the tricky part will be building it out for all of the possibilities on this command.

**Comment by jmcgill298** [comment]
please open a pull request with only the intended files updated

**Pull request closed without merging**
