### PR TITLE
add PANOS license info

### PR DESCRIPTION
**Pull request by jdinocco**

### CODE REVIEW

**Comment by ryanmerolle** [comment]
@jdinocco do you have raw input you can test against?

**Comment by jdinocco** [comment]
Hi Ryan! sorry for the late response.

Here's a example from Palo Alto kb (https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000Cm0BCAS)

`admin@PA-VM> request license info

Current PDT Date: May 19, 2021

License entry:
Feature: WildFire License
Description: WildFire signature feed, integrated WildFire logs, WildFire API
Serial: 0000000xxxxxxxx
Issued: January 13, 2020
Expires: March 08, 2023
Expired?: no
Base license: PA-VM

License entry:
Feature: Premium
Description: 24 x 7 phone support; advanced replacement hardware service
Serial: 0000000xxxxxxxx
Issued: January 13, 2020
Expires: January 09, 2023
Expired?: no
Base license: PA-VM

License entry:
Feature: PAN-DB URL Filtering
Description: Palo Alto Networks URL Filtering License
Serial: 0000000xxxxxxxx
Issued: January 13, 2020
Expires: March 08, 2023
Expired?: no
Base license: PA-VM

License entry:
Feature: GlobalProtect Portal
Description: GlobalProtect Portal License
Serial: 0000000xxxxxxxx
Issued: March 08, 2017
Expires: Never
Expired?: no
Base license: PA-VM

License entry:
Feature: PA-VM
Description: Standard VM-100
Serial: 0000000xxxxxxxx
Issued: March 08, 2017
Expires: Never
Expired?: no

License entry:
Feature: Threat Prevention
Description: Threat Prevention
Serial: 0000000xxxxxxxx
Issued: January 13, 2020
Expires: January 13, 2023
Expired?: no
Base license: PA-VM

License entry:
Feature: GlobalProtect Gateway
Description: GlobalProtect Gateway License
Serial: 0000000xxxxxxxx
Issued: January 13, 2020
Expires: March 08, 2023
Expired?: no
Base license: PA-VM`

**Comment by ryanmerolle** [comment]
see #1718 for an example on how to test in the PR

**Comment by jmcgill298** [comment]
replaced by https://github.com/networktocode/ntc-templates/pull/1775

**Pull request closed without merging**
