### PR TITLE
New Template - CISCO IOS - Show Module

### PR DESCRIPTION
**Pull request by alekgozali**
Added Show Module

##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

Template : show module
os : cisco_ios
command : show module

##### SUMMARY

this version added with show module output, textfsm will parse all the output into the dictionary

```

```

### CODE REVIEW

**Comment by alekgozali** [comment]
Added Show etherchannel summary

**Comment by FragmentedPacket** [comment]
@alekgozali We're discussing this internally in regards to the `show_module`, but in the mean time, do you minding splitting this PR up into individual PRs per template? You can keep all the `show_module` templates in here, but move out the other two and the necessary data/yaml files as well.

**Comment by alekgozali** [comment]
> @alekgozali We're discussing this internally in regards to the `show_module`, but in the mean time, do you minding splitting this PR up into individual PRs per template? You can keep all the `show_module` templates in here, but move out the other two and the necessary data/yaml files as well.

Hi @FragmentedPacket , i have modified it , only show module added on this PR,
i'm quite new to git and i hope i can contribute more for this ntc-template, 
i had prepared few modules ( show mpls ldp neighbour, show mpls interface, show etherchannel summary ) which haven't added yet to this template.
how we can generate .yaml file from .raw ? is there any way to be generated automatically

**Comment by FragmentedPacket** [comment]
We appreciate any contributions we get!

Here is some scripts developed by @jmcgill298 and are detailed in our [README](https://github.com/networktocode/ntc-templates#development-helper-scripts)

You can submit each template into their own PRs so we can review and get those merged in sooner as well.

**Pull request merged**
