### PR TITLE
CISCO XR SHOW BGP NEIGH: Add new template

### PR DESCRIPTION
**Pull request by jmcgill298**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

cisco_xr_show_bgp_neighbor

##### SUMMARY

Add new template

```

```

### CODE REVIEW

**Comment by jmcgill298** [comment]
@jtishey I updated the template to include matches for each line; can you take a look at my changes/updates and let me know what you think?

**Comment by jtishey** [comment]
thanks @jmcgill298 ,  I checked it against a few different routers and will look at making a few updates for neighbors with Graceful Restart enabled and add the raw text for it.

**Comment by jtishey** [comment]
@jmcgill298  After testing on a few routers with different configs/versions, I've made some additions @ https://github.com/jtishey/ntc-templates/commit/9cb694f8809a22f40f38ad1cf3b010f9f1a1493e

Do you want a new PR or just review and integrate it with yours?

Added tests/cisco_xr/show_bgp_neighbors1.raw
Added tests/cisco_xr/show_bgp_neighbors1.parsed
Updated templates/cisco_xr_show_bgp_neighbors.templates
```
Value GR (.+?)
Value List DEFAULT_ORIGINATE (.+)
Value LAST_RESET_REASON (.*)

START
  ^\s+Remote\s+AS\s+${REMOTE_AS}\,\s+local\s+AS\s+${LOCAL_AS}\,\s+(?:no\-prepend,\s+)?(?:replace\-as\,\s+)?${TYPE}\s+link
  ^\s+Administratively\s+shut\s+down
  ^\s+BFD\s+[Ee]nabled
  ^\s+Configured hold time\:\s+\d+\,\s+keepalive\:
  ^\s+Graceful\s+restart\s+is\s+${GR}\s*$$
  ^\s+Restart\s+time\s+is
  ^\s+Stale\s+path\s+timeout\s+time\s+is
  ^\s+Graceful\s+Restart\s+\(GR\s+Awareness\)\:
  ^\s+Inbound\s+message\s+logging
  ^\s+Outbound\s+message\s+logging

AFI
  ^\s+Default\s+information\s+originate\:\s+${DEFAULT_ORIGINATE}
  ^\s+AF-dependent capabilities
  ^\s+Graceful\s+Restart\s+capability
  ^\s+Local\s+restart\s+time\s+is
  ^\s+Maximum\s+stalepath\s+time\s+is
  ^\s+Remote\s+Restart\s+time\s+is
  ^\s+Private\s+AS\s+number\s+removed
  ^\s+Community\s+attribute
  ^\s+Advertise\s+VPNv[46]\s+routes\s+(is\s)?enabled\s+with
  ^\s+AS\s+[oO]verride\s+is
  ^\s+Send\s+Multicast\s+Attributes

CONNECTION
  ^\s+Last\s+reset\s+${LAST_RESET}\,\s+due\s+to\s+${LAST_RESET_REASON}
  ^\s+Last\s+reset\s+${LAST_RESET}
  ^\s+External\s+BGP\s+neighbor\s+not\s+directly
```

**Comment by jtishey** [comment]
#346 opened against branch xr_show_bgp_neigh

**Comment by jmcgill298** [comment]
Thanks @jtishey

**Pull request merged**
