### PR TITLE
Cisco ios show ip bgp summary

### PR DESCRIPTION
**Pull request by PavloSkliarenko**
I\`m kinda new to Github. So I don`t realy sure about: is my new commits are visible in PR after your change request. So I closed my [previous PR](https://github.com/networktocode/ntc-templates/pull/1433) and opened this one

### CODE REVIEW

**Comment by mjbear** [comment]
Hello @PavloSkliarenko,

Yes, your changes/diffs can be found on the Files Changed tab near the top of the PR.
https://github.com/networktocode/ntc-templates/pull/1442/files

**Comment by PavloSkliarenko** [comment]
@jvanderaa Take a look at this fix, please. I`ve added new values and fixed the names of old ones to be more understandable

**Comment by mjbear** [comment]
@PavloSkliarenko
I'm just a community member, but I'd like to thank you for your contributions.

There is an "unofficial" effort to **_normalize_ "common" capture group names** across templates of similar uses (for all vendors). Although the PR #1468 hasn't been merged into the mainline yet, there is a document I hope to keep up-to-date (which with your changes here needs updates) and make these updates across all vendors' templates where appropriate.

Maybe it's possible to brainstorm some standard capture group names for common ones. Sound like something you're interested in?

I too plan to bug @jvanderaa and @itdependsnetworks a bit to see that this documentation PR makes it to mainline sooner than later so each template contribution not only has documentation but should also comply with established "standard" capture group names. :smile:

**Comment by jvanderaa** [comment]
This looks good. I will plan to get a new major release out in the next 2 weeks or less.

**Review by pszulczewski — APPROVED** [review]

**Pull request merged**
