### PR TITLE
Update juniper_junos_show_ethernet-switching_table.textfsm

### PR DESCRIPTION
**Pull request by microsoftdealer**
Replacement for 14th line - Template is pretty good, but this line doesn't match real pattern.
Tested on Junos version 14.1X53-D47.6, hardware - qfx3500s

ISSUE TYPE

Bugfix Pull Request
COMPONENT

Juniper-JunOS 14.1X53-D47.6-show ethernet-switching table

SUMMARY

Template is pretty good, but this line doesn't match real pattern.

SAMPLE OUTPUT that cannot be parsed with current template but can be parsed with my fix:
"""
MAC flags (S - static MAC, D - dynamic MAC, L - locally learned, P - Persistent static
SE - statistics enabled, NM - non configured MAC, R - remote PE MAC, O - ovsdb MAC)

Ethernet switching table : 2 entries, 2 learned
Routing instance : default-switch
Vlan MAC MAC Age Logical
name address flags interface
BD-903691 3c:8c:93:50:dc:c0 D - ae2.0
BD-903691 52:54:00:f5:30:2b D - ae2.0

MAC flags (S - static MAC, D - dynamic MAC, L - locally learned, P - Persistent static
SE - statistics enabled, NM - non configured MAC, R - remote PE MAC, O - ovsdb MAC)

Ethernet switching table : 9 entries, 9 learned
Routing instance : default-switch
    Vlan                MAC                 MAC         Age    Logical
    name                address             flags              interface
    Vlan3117            00:00:5e:00:dd:dd   D             -   ae2.0
    Vlan3117            00:0c:29:07:f6:65   D             -   ae2.0
    Vlan3117            00:0c:29:84:d2:f8   D             -   xe-0/0/3.0
    Vlan3117            00:0c:29:8e:7e:a1   D             -   xe-0/0/2.0
    Vlan3117            00:0c:29:93:49:03   D             -   ae2.0
    Vlan3117            00:0c:29:e8:66:21   D             -   xe-0/0/3.0
    Vlan3117            3c:8c:93:50:dc:00   D             -   ae2.0
    Vlan3117            3c:8c:93:50:dc:c0   D             -   ae2.0
    Vlan3117            88:e6:4b:af:51:00   D             -   ae2.0

MAC flags (S - static MAC, D - dynamic MAC, L - locally learned, P - Persistent static
           SE - statistics enabled, NM - non configured MAC, R - remote PE MAC, O - ovsdb MAC)

Ethernet switching table : 45 entries, 45 learned
Routing instance : default-switch
    Vlan                MAC                 MAC         Age    Logical
    name                address             flags              interface
    v290                00:00:5e:00:dd:dd   D             -   ae2.0
    v290                00:50:56:b8:03:2d   D             -   xe-0/0/2.0
    v290                00:50:56:b8:03:6d   D             -   ae2.0
    v290                00:50:56:b8:05:df   D             -   xe-0/0/1.0
    v290                00:50:56:b8:08:d8   D             -   xe-0/0/2.0
    v290                00:50:56:b8:1c:58   D             -   xe-0/0/1.0
    v290                00:50:56:b8:20:56   D             -   xe-0/0/2.0
    v290                00:50:56:b8:26:06   D             -   xe-0/0/3.0
    v290                00:50:56:b8:28:88   D             -   xe-0/0/2.0
    v290                00:50:56:b8:29:50   D             -   ae2.0
    v290                00:50:56:b8:32:96   D             -   xe-0/0/2.0
    v290                00:50:56:b8:39:74   D             -   ae2.0
    v290                00:50:56:b8:3c:7b   D             -   xe-0/0/2.0
    v290                00:50:56:b8:47:ac   D             -   ae2.0
    v290                00:50:56:b8:48:ac   D             -   xe-0/0/1.0
    v290                00:50:56:b8:4b:94   D             -   xe-0/0/1.0
    v290                00:50:56:b8:57:b1   D             -   xe-0/0/2.0
    v290                00:50:56:b8:58:85   D             -   xe-0/0/2.0
    v290                00:50:56:b8:5b:87   D             -   xe-0/0/2.0
    v290                00:50:56:b8:60:e2   D             -   xe-0/0/2.0
    v290                00:50:56:b8:63:ee   D             -   xe-0/0/2.0
    v290                00:50:56:b8:75:07   D             -   ae2.0
    v290                00:50:56:b8:79:35   D             -   ae2.0
    v290                00:50:56:b8:7b:4a   D             -   xe-0/0/1.0
    v290                00:50:56:b8:7e:61   D             -   xe-0/0/2.0
    v290                00:50:56:b8:8a:2a   D             -   ae2.0
    v290                00:50:56:b8:91:b5   D             -   ae2.0
    v290                00:50:56:b8:96:ae   D             -   xe-0/0/3.0
    v290                00:50:56:b8:98:ec   D             -   xe-0/0/3.0
    v290                00:50:56:b8:9b:c0   D             -   xe-0/0/3.0
    v290                00:50:56:b8:a5:a0   D             -   ae2.0
    v290                00:50:56:b8:ba:58   D             -   xe-0/0/1.0
    v290                00:50:56:b8:bf:72   D             -   ae2.0
    v290                00:50:56:b8:c3:1c   D             -   ae2.0
    v290                00:50:56:b8:d1:28   D             -   xe-0/0/3.0
    v290                00:50:56:b8:d9:d7   D             -   xe-0/0/2.0
    v290                00:50:56:b8:dd:b7   D             -   xe-0/0/1.0
    v290                00:50:56:b8:e4:f1   D             -   xe-0/0/2.0
    v290                00:50:56:b8:e9:ee   D             -   xe-0/0/1.0
    v290                00:50:56:b8:f2:e4   D             -   ae2.0
    v290                00:50:56:b8:f6:de   D             -   xe-0/0/1.0
    v290                00:50:56:b8:fb:a5   D             -   xe-0/0/2.0
    v290                3c:8c:93:50:dc:00   D             -   ae2.0
    v290                3c:8c:93:50:dc:c0   D             -   ae2.0
    v290                88:e6:4b:af:51:00   D             -   ae2.0

### CODE REVIEW

**Comment by jvanderaa** [comment]
This fails at the moment. Making the change from `Vlan${VLAN}` to just `${VLAN}` causes the output such as the following on https://github.com/networktocode/ntc-templates/blob/master/tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table.raw:

```

MAC flags (S - static MAC, D - dynamic MAC, L - locally learned, P - Persistent static, C - Control MAC
           SE - statistics enabled, NM - non configured MAC, R - remote PE MAC, O - ovsdb MAC)


Ethernet switching table : 3 entries, 3 learned
Routing instance : default-switch
    Vlan                MAC                 MAC         Age    Logical                NH        RTR
    name                address             flags              interface              Index     ID
    Vlan2               bc:ac:0a:ca:ca:30   DR            -   ae3.0                  0         0
    Vlan100             2c:5a:0f:bc:a3:cd   DL            -   xe-0/0/51:0.0          0         0
    Vlan1011            ca:fe:ca:fe:00:07   DL            -   ae100.0                0         0

{master:0}
```

This would take the output from `2` to `Vlan2`. Breaking automations. The tests did not run, but manual testing with the tox command shows the failure.

```
================================================================================== FAILURES ==================================================================================
_______________________ test_raw_data_against_mock[tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table1.raw] _______________________

load_template_test = 'tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table1.raw'

    def test_raw_data_against_mock(load_template_test):
        processed, reference = raw_template_test(load_template_test)

        correct_number_of_entries_test(processed, reference)
        all_entries_have_the_same_keys_test(processed, reference)
>       correct_data_in_entries_test(processed, reference)

tests/test_structured_data_against_parsed_reference_files.py:50:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

processed = [{'age': '-', 'logical_interface': 'ae112.0', 'mac_address': '2c:5a:0f:bc:a3:cd', 'mac_flag': 'DL', ...}, {'age': '-', 'logical_interface': 'ae112.0', 'mac_address': 'ca:fe:ca:fe:00:07', 'mac_flag': 'DL', ...}]
reference = [{'age': '-', 'logical_interface': 'ae112.0', 'mac_address': '2c:5a:0f:bc:a3:cd', 'mac_flag': 'DL', ...}, {'age': '-', 'logical_interface': 'ae112.0', 'mac_address': 'ca:fe:ca:fe:00:07', 'mac_flag': 'DL', ...}]

    def correct_data_in_entries_test(processed, reference):
        """Test that the actual data in each entry is the same as the control.

        This will create a test for each of the files in the test_collection
        variable.
        """
        # Can be uncommented if we don't care that the parsed data isn't
        # in the same order as the raw data
        # reference = sorted(reference)
        # processed = sorted(processed)

        for i in range(len(reference)):
            for key in reference[i].keys():
>               assert processed[i][key] == reference[i][key], "entry #{0}, key: {1}".format(
                    i, key
                )
E               AssertionError: entry #0, key: vlan
E               assert 'Vlan100' == '100'
E                 - 100
E                 + Vlan100

tests/test_structured_data_against_parsed_reference_files.py:88: AssertionError
_______________________ test_raw_data_against_mock[tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table.raw] ________________________

load_template_test = 'tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table.raw'

    def test_raw_data_against_mock(load_template_test):
        processed, reference = raw_template_test(load_template_test)

        correct_number_of_entries_test(processed, reference)
        all_entries_have_the_same_keys_test(processed, reference)
>       correct_data_in_entries_test(processed, reference)

tests/test_structured_data_against_parsed_reference_files.py:50:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

processed = [{'age': '-', 'logical_interface': 'ae3.0', 'mac_address': 'bc:ac:0a:ca:ca:30', 'mac_flag': 'DR', ...}, {'age': '-', '...': 'DL', ...}, {'age': '-', 'logical_interface': 'ae100.0', 'mac_address': 'ca:fe:ca:fe:00:07', 'mac_flag': 'DL', ...}]
reference = [{'age': '-', 'logical_interface': 'ae3.0', 'mac_address': 'bc:ac:0a:ca:ca:30', 'mac_flag': 'DR', ...}, {'age': '-', '...': 'DL', ...}, {'age': '-', 'logical_interface': 'ae100.0', 'mac_address': 'ca:fe:ca:fe:00:07', 'mac_flag': 'DL', ...}]

    def correct_data_in_entries_test(processed, reference):
        """Test that the actual data in each entry is the same as the control.

        This will create a test for each of the files in the test_collection
        variable.
        """
        # Can be uncommented if we don't care that the parsed data isn't
        # in the same order as the raw data
        # reference = sorted(reference)
        # processed = sorted(processed)

        for i in range(len(reference)):
            for key in reference[i].keys():
>               assert processed[i][key] == reference[i][key], "entry #{0}, key: {1}".format(
                    i, key
                )
E               AssertionError: entry #0, key: vlan
E               assert 'Vlan2' == '2'
E                 - 2
E                 + Vlan2

tests/test_structured_data_against_parsed_reference_files.py:88: AssertionError
============================================================================== warnings summary ==============================================================================
.tox/py38/lib/python3.8/site-packages/textfsm/terminal.py:203
  /Users/joshv/Developer/ntc-templates/.tox/py38/lib/python3.8/site-packages/textfsm/terminal.py:203: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if token is '':

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================== short test summary info ===========================================================================
FAILED tests/test_structured_data_against_parsed_reference_files.py::test_raw_data_against_mock[tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table1.raw]
FAILED tests/test_structured_data_against_parsed_reference_files.py::test_raw_data_against_mock[tests/juniper_junos/show_ethernet-switching_table/juniper_junos_show_ethernet-switching_table.raw]
================================================================= 2 failed, 1204 passed, 1 warning in 18.41s =================================================================
ERROR: InvocationError for command /Users/joshv/Developer/ntc-templates/.tox/py38/bin/python -m pytest -v (exited with code 1)
__________________________________________________________________________________ summary ___________________________________________________________________________________
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
ERROR:   py38: commands failed
```

To run the tox results outside of the repo:

```
poetry run tox -e py36,py37,py38
```

**Review by jvanderaa — CHANGES_REQUESTED** [review]

**Comment by microsoftdealer** [comment]
@jvanderaa , your tests are not familiar with vlan naming in JunOS show ethernet-switching table. This is not vlan numbers, but vlan names. There is a good practice to set namings like "VlanXX", but in my case you can see output with vlan naming like "v290", and you can see that in my sample output. So, to be correct, you cant use textfsm for parsing vlan number before my fix. And even after my fix - you are still parsing only vlan NAME. This numbers are not always the same with real vlans. So, I advice you to fix the samples and assertions for tests

**Comment by microsoftdealer** [comment]
Reference links are available at JunOS https://www.juniper.net/documentation/us/en/software/junos/multicast-l2/topics/ref/command/show-ethernet-switching-table-qfx-series.html#show-ethernet-switching-table-command__d19652e324

**Comment by jvanderaa** [comment]
Thanks, that makes sense. I'll remove the required change there. But the tests as written are failing at this point.

**Review by jvanderaa — COMMENTED** [review]
Will need to have some changes done for the tests that are failing with the update.

**Comment by jmcgill298** [comment]
https://github.com/networktocode/ntc-templates/pull/1733 addresses @jvanderaa concerns, accounts for BD, and adds the test cases

**Pull request closed without merging**
