### PR TITLE
Add allied telesis templates

### PR DESCRIPTION
**Pull request by dainok**
The PR adds some templates for Allied Telesis AW+ devices:

- allied_telesis_awplus_show_arp.textfsm
- allied_telesis_awplus_show_etherchannel_summary.textfsm
- allied_telesis_awplus_show_interface.textfsm
- allied_telesis_awplus_show_interface_switchport.textfsm
- allied_telesis_awplus_show_ip_route.textfsm
- allied_telesis_awplus_show_lldp_neighbors_detail.textfsm
- allied_telesis_awplus_show_mac_address-table.textfsm
- allied_telesis_awplus_show_static-channel-group.textfsm
- allied_telesis_awplus_show_system.textfsm
- allied_telesis_awplus_show_vlan_all.textfsm

### CODE REVIEW

**Comment by dainok** [comment]
Requested by https://github.com/dainok/netdoc/pull/122

**Comment by evilmonkey19** [comment]
Hi! I see all the effort you put in this request. I would suggest dividing all the commands in different pull requests so it's easier for @jvanderaa to do the code review.

If you want, I don't mind helping you with that.

Btw, I have seen that you are working on L2-L3 mapper for Netbox. Would it be easy to port it to Nautobot as well?

**Comment by dainok** [comment]
Hi @evilmonkey19 
thank you for your attention.
1. No worries, I can split the PR into multiple requests, I'll work on that in the next days.
2. I planned to port NetDoc into Nautobot too, but I had to delayed because of my job. Do you think NTC could be interested in Netdoc?

**Comment by evilmonkey19** [comment]
Specifically me, unfortunately, I don't work at NTC but I would love to see such features in Nautobot. We are always doing network maps. Currently, we do most of them by hand. I had the intention to do a similar tools a few years back (just a crawler), but not as advance as yours.

**Comment by dainok** [comment]
@evilmonkey19 : I opened the 10 PR :)

**Pull request closed without merging**
