### PR TITLE
Normalize CDP, LLDP, ISDP capture groups

### PR DESCRIPTION
**Pull request by mjbear**
Normalization across several "discovery protocols", largely CDP and LLDP (though I did find broadcom_icos had ISDP as well). This huge effort started as a comment on #1405 and includes numerous capture group changes so it is likely the community will notice the *****breaking changes***** this PR brings.

Based off of #1468 so capture group documentation would end up in `data_model.md`

**To the community:** If I broke something, point it out, if I have time chances are I'll take ownership and fix it, but if not please realize I had good intentions and submit fix(es) in PR(s) to `ntc-templates`.

**Hopefully all of this normalization brings positive change and improved usability for the project in the long term.**

NOTE: it does seem like example raw Cisco IOS LLDP output had some data seemingly swapped (whether that's the LLDP sending or receiving end), but we end up with the output we have.

- https://github.com/networktocode/ntc-templates/blob/master/tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail2.yml
- https://github.com/networktocode/ntc-templates/blob/master/tests/cisco_ios/show_lldp_neighbors_detail/cisco_ios_show_lldp_neighbors_detail2.raw 
- https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/cisco_ios_show_lldp_neighbors_detail.textfsm

### CODE REVIEW

**Comment by mjbear** [comment]
I am fixing up merge conflicts and putting this on @jvanderaa 's list :sweat_smile:

**Comment by mjbear** [comment]
ironed out some merge conflicts

**Comment by mjbear** [comment]
rebasing off of current NTC master branch to help alleviate merge conflicts for the maintainers

**Comment by ryanmerolle** [comment]
Is this close?  Happy to help.

**Comment by mjbear** [comment]
Hello @ryanmerolle,

This was waiting to be merged. (It was ready.)
I'll see if I can make time to rebase it off the current main branch so Josh doesn't have merge conflicts and so on.

Thank you

**Comment by jvanderaa** [comment]
Thanks @mjbear I thought that I had all of them from earlier.

**Comment by mjbear** [comment]
This has been rebased.

**Review by jvanderaa — APPROVED** [review]

**Pull request merged**
