### PR TITLE
add data model documentation

### PR DESCRIPTION
**Pull request by mjbear**
Data model documentation to share guidance on capture group normalization.

### CODE REVIEW

**Comment by mjbear** [comment]
@dainok
Here's a start on the data model for normalized capture group names. As you pointed out on #1405, CDP/LLDP is one that could be normalized. Although CDP/LLDP isn't normalized yet, I am working up a plan for the plethora of capture groups that match up with each other. :grin: 

If you're interested in weighing in on the CDP/LLDP I could copy you in.

**Comment by dainok** [comment]
> @dainok Here's a start on the data model for normalized capture group names. As you pointed out on #1405, CDP/LLDP is one that could be normalized. Although CDP/LLDP isn't normalized yet, I am working up a plan for the plethora of capture groups that match up with each other. 😁
> 
> If you're interested in weighing in on the CDP/LLDP I could copy you in.

Yes please (sorry for the late response)

**Comment by mjbear** [comment]
> > @dainok Here's a start on the data model for normalized capture group names. As you pointed out on #1405, CDP/LLDP is one that could be normalized. Although CDP/LLDP isn't normalized yet, I am working up a plan for the plethora of capture groups that match up with each other. 😁
> > If you're interested in weighing in on the CDP/LLDP I could copy you in.
> 
> Yes please (sorry for the late response)

@dainok 
Please give PR #1469 a look if you have time.

**Comment by mjbear** [comment]
Did I accidentally close this?

**Comment by jvanderaa** [comment]
It was tied to #1582

**Pull request closed without merging**
