### PR TITLE
Standardize capture group IP_ADDRESS

### PR DESCRIPTION
**Pull request by mjbear**
Standardization/normalization instances of ADDRESS
Breaking change on account of the capture group changes

- ADDRESS > MAC_ADDRESS plus make the MAC_ADDRESS regex more concise for paloalto_panos show_inteface_hardware
- replace some instances of ADDRESS with IP_ADDRESS
- replace some instances of ADDRESS with MAC_ADDRESS
- split ADDRESS into its parts IP_ADDRESS and PREFIX_LENGTH (ex: arista show ip ospf interface)
- split IP_ADDRESS into its parts IP_ADDRESS and PREFIX_LENGTH
- regenerate yaml for fortinet get_system_interface and get_system_interface_physical
- replace IP with IP_ADDRESS for most replace IP with IP_STATE for alcatel_aos_show_vlan
- split IP into its parts IP_ADDRESS and PREFIX_LENGTH for aruba_aoscx_show_ip_route_all-vrfs
- replace capture group IPADDRESS with IP_ADDRESS
- replace capture group IP_ADDR with IP_ADDRESS
- replace capture group IPADDR with IP_ADDRESS

### CODE REVIEW

**Review by itdependsnetworks — APPROVED** [review]

**Comment by dainok** [comment]
Hi @mjbear / @itdependsnetworks / @jvanderaa 

I think there is an error on new `ntc_templates/templates/cisco_nxos_show_interface.textfsm`

In the old template address (mac_address) were reported, on the new are missing:

~~~
tests/cisco_nxos/show_interface/cisco_nxos_show_interface.yml

- address: "5087.89a1.d8d5"
+ mac_address: ""
~~~

The template has been modified as following:

~~~
ntc_templates/templates/cisco_nxos_show_interface.textfsm

- ^\s+Hardware(:|\s+is)\s+${HARDWARE_TYPE},\s+address(:|\s+is)\s+${ADDRESS}(.*bia\s+${BIA})*
+ ^\s+Hardware(:|\s+is)\s+${HARDWARE_TYPE},\s+address(:|\s+is)\s+${IP_ADDRESS}\/${PREFIX_LENGTH}(.*bia\s+${BIA})*
~~~

The error is about replacing IP_ADDRESS instead of MAC_ADDRESS.

**Comment by mjbear** [comment]
@dainok

Yes.
I believe I changed line 28 in error instead of updating line 30. Because ADDRESS was used for both IP addresses and MAC addresses in some cases, I manually viewed any file with the capture group ADDRESS.

My apologies.

I appreciate you noticing this so it can be fixed before a point release.

**Comment by mjbear** [comment]
@dainok
Thank you once again for pointing out this mistake.
The test YAML looks so much better now. :confounded: 

@jvanderaa / @itdependsnetworks 
Apologies for the mistake.
PR #1444 is out there to resolve my mistake.

**Comment by dainok** [comment]
Thank you @mjbear you are doing a great job!

**Pull request merged**
