### PR TITLE
add cisco_wlc_ssh_show_exclusionlist

### PR DESCRIPTION
**Pull request by ancker010**
##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
Cisco WLC SSH, 'show exclusionlist'.

##### SUMMARY
Template will read MAC addresses and comments from the Cisco WLC exclusionlist.

### CODE REVIEW

**Comment by jvanderaa** [comment]
I'm seeing that the exclusionlist has a bunch of manually generated exclusions (makes sense). Would it also catch the dynamically excluded clients?

Asking as someone that is particularly interested in doing a few more WLC SSH templates in the future.

**Comment by ancker010** [comment]
> I'm seeing that the exclusionlist has a bunch of manually generated exclusions (makes sense). Would it also catch the dynamically excluded clients?
> 
> Asking as someone that is particularly interested in doing a few more WLC SSH templates in the future.

I'm not sure. I don't have any in my production system so I wasn't able to test for that.
I assume it follows the same format, but instead of Description there is a "Reason" or something that caused the dynamic exclusion.

**Comment by ancker010** [comment]
Done.

**Comment by FragmentedPacket** [comment]
Sorry that wasn't the complete change was just a suggestion:
```
Value MAC (([\da-fA-F]{2}[-:]){5}[\da-fA-F]{2})
Value COMMENT (.*)

Start
  ^Manually\s*Disabled\s*Clients -> ManuallyDisabled
  ^No\s*dynamically
  ^\s*$$
  ^. -> Error

ManuallyDisabled
  ^---
  ^MAC\s+Address\s+Description
  ^${MAC}\s+${COMMENT} -> Record
  ^\s*$$ -> Start
```

**Comment by ancker010** [comment]
Sorry. Regex isn't my strong suit.
Updated and tests pass.

**Pull request merged**
