### PR TITLE
Re-created cisco_asa_show_interface.template

### PR DESCRIPTION
**Pull request by jvanderaa**
- Moved where the record was to continue on gathering information even when the field was not found

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT

cisco_asa_show_interface.template
Cisco ASA
`show interface`

##### SUMMARY

Moved the location of the record in order to continue on creating records even when there were no PPS or other items to find.

```

```

### CODE REVIEW

**Comment by jmcgill298** [comment]
@jvanderaa your branch has conflicts that needs to be resolved. I'll take a look once it is resolved.

**Comment by jmcgill298** [comment]
@jvanderaa the issue is that you are recording before all the data is collected on the first iteration, so the first interface does not get it's stats recorded. Please either update the existing test files with sample data representative of your environment, or add new files that accurately reflects your environment so we can ensure any future change to the template does not break existing use-cases.

Once you provide updates to include your data, I will help with the template to make sure all data is captured appropriately.

**Comment by jvanderaa** [comment]
I've updated the raw output with #209. It's a much shorter output.

**Comment by jmcgill298** [comment]
@jvanderaa can we close this request then? Also, I put a PR into your branch for #209

**Comment by jvanderaa** [comment]
I had this one setup to create a record once it had the minimum amount of data (I think that is how it works??). The other PR had just the RAW test data if I did it right.

**Comment by jmcgill298** [comment]
@jvanderaa New PRs should have a minimum of 3 file updates for new templates and patching bugs:

1. template file
2. raw file
3. parsed file matching parsed data from raw

https://github.com/jvanderaa/ntc-templates/pull/1 is a PR I put in to your branch to add the parsed data mapping to your updated raw data. I also changed the Record statements so that it should capture all of the data for both physical and virtual interfaces. Can you pull that down and test? If you merge it then, it should update #209 and be a complete PR.

**Comment by jvanderaa** [comment]
Sounds good. We can close this out with this.

**Comment by jmcgill298** [comment]
Closing as #209 should handle this

**Pull request closed without merging**
