### PR TITLE
modified:   cisco_ios_show_cdp_neighbors_detail.template

### PR DESCRIPTION
**Pull request by tsimson**
##### ISSUE TYPE

 - Additional Testing

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
@tsimson can you provide sample data and expected output? This will help us understand corner cases we are missing.

**Comment by tsimson** [comment]
Certainly,

This seems to exit the template if there is no IP address configured on the neighbor:
ParseIP
  ^.*IP address: ${MANAGEMENT_IP} -> Start

Here is some sample output from before the change:
Before:
ok: [vIOS-1] => {
    "output": {
        "changed": false,
        "response": [
            {
                "destination_host": "vIOS-L2-1",
                "local_host": "",
                "local_port": "",
                "management_ip": "",
                "platform": "",
                "remote_port": "",
                "software_version": ""
            }
        ],
        "response_list": []
    }
}

The additional line fixes this by detecting the "^Platform" line and simply continuing the template:
ParseIP
  ^.*IP address: ${MANAGEMENT_IP} -> Start
  ^Platform: -> Start

Here is the same output after the change:
After:
ok: [vIOS-1] => {
    "output": {
        "changed": false,
        "response": [
            {
                "destination_host": "vIOS-L2-1",
                "local_host": "",
                "local_port": "GigabitEthernet0/2",
                "management_ip": "",
                "platform": "",
                "remote_port": "GigabitEthernet0/2",
                "software_version": "Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Version 15.2(CML_NIGHTLY_20150414)FLO_DSGS7, EARLY DEPLOYMENT DEVELOPMENT BUILD, synced to  DSGS_PI5_POSTCOLLAPSE_TEAM_TRACK_CLONE"
            }
        ],
        "response_list": []
    }
}

Hope this provides clarification,
Tim

**Comment by itdependsnetworks** [comment]
Can you take a look at tests/cisco_ios/show_cdp_neighbor_detail/ and create an additional raw and parsed file with your test data?

**Comment by tsimson** [comment]
@itdependsnetworks I combined the new command raw output with the existing test for that command. Does that fly?

**Comment by itdependsnetworks** [comment]
@tsimson that should work, much appreciated. Let's just check in with @GGabriele to see if he has any inputs.

**Comment by GGabriele** [comment]
Everything looks good now, thanks @tsimson !

**Pull request merged**
