### PR TITLE
Alcatel aos show linkagg port

### PR DESCRIPTION
**Pull request by evilmonkey19**

### CODE REVIEW

**Comment by evilmonkey19** [comment]
> @evilmonkey19 It looks like this template was merged in yesterday; if you are wanting to make some updates to the template, then resolve the conflicts and we can get this merged in

That's true. The main issue is that I didn't know al the possible outputs. I generally build these templates based on the current output in the script I do

**Comment by jmcgill298** [comment]
> > @evilmonkey19 It looks like this template was merged in yesterday; if you are wanting to make some updates to the template, then resolve the conflicts and we can get this merged in
> 
> That's true. The main issue is that I didn't know al the possible outputs. I generally build these templates based on the current output in the script I do

I'm just not sure what should be done to resolve conflicts, I can give it a try and see if that is what you intend

**Comment by jmcgill298** [comment]
@evilmonkey19 please verify this looks good after I resolved the conflicts

**Review by jmcgill298 — APPROVED** [review]

**Comment by evilmonkey19** [comment]
To me everything seems fine! :)

**Comment by jmcgill298** [comment]
> To me everything seems fine! :)

Thanks

**Pull request merged**
