### PR TITLE
Check Point Gaia: Support some show commands

### PR DESCRIPTION
**Pull request by alexanderhofmann**
##### ISSUE TYPE
 - New Template Pull Request

##### COMPONENT
checkpoint_gaia_cpinfo.template, checkpoint_gaia, cpinfo                                              
checkpoint_gaia_show_asset_all.template, checkpoint_gaia, show asset all                              
checkpoint_gaia_show_domainname.template, checkpoint_gaia, show domainname                            
checkpoint_gaia_show_interfaces_all.template, checkpoint_gaia, show interfaces all                    
checkpoint_gaia_show_ipv6_route.template, checkpoint_gaia, show ipv6 route                                                                                                                                      
checkpoint_gaia_show_lom.template, checkpoint_gaia, show lom                                          
checkpoint_gaia_show_route.template, checkpoint_gaia, show route                                      
checkpoint_gaia_show_version_all.template, checkpoint_gaia, show version all

##### SUMMARY
New templates for Check Point Gaia Firewall commands

### CODE REVIEW

**Comment by GGabriele** [comment]
Hi @alexanderhofmann , thanks for your contribution!

Can you please add some sample outputs and expected parsed files to test your new templates against?
[Check this directories for examples](https://github.com/networktocode/ntc-templates/tree/master/tests)

**Comment by itdependsnetworks** [comment]
@alexanderhofmann Would love to include these, any chance you can add tests?

**Comment by alexanderhofmann** [comment]
Hi, sorry for the long delay. I'll have a look on this tomorrow.

**Comment by itdependsnetworks** [comment]
Not sure where this one is at, let me know if you need anything from our side.

**Comment by alexanderhofmann** [comment]
@itdependsnetworks these are the testcases I wrote a couple of weeks ago. Can't figure out why all of them don't work. Do you have any hints for me?

**Comment by itdependsnetworks** [comment]
mv `/checkpoint_gaia/show_version_all.parsed -> /checkpoint_gaia/checkpoint_gaia_show_version_all.parsed` as an example but for all of them. You can run tests locally by installing pytest and running py.test.

**Comment by jmcgill298** [comment]
@alexanderhofmann I fixed the index file order, and then I accidentally pushed it to your upstream instead of mine, and that closed it. Can you reopen with the checkpoint files, and I will merge

**Comment by jmcgill298** [comment]
These have been merged

**Pull request closed without merging**
