### PR TITLE
Update setup.py install_requires from gtextfsm->textfsm

### PR DESCRIPTION
**Pull request by johnarnold**
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT
setup

##### SUMMARY
Setup.py install_requires was referencing an old, unmaintained package.  Updated to reference the current textfsm package.

### CODE REVIEW

**Comment by johnarnold** [comment]
gtextfsm is way out of date.  textfsm is current.  gtextfsm implements module namespace, so imports have to change for textfsm.

**Comment by itdependsnetworks** [comment]
I'll ping @jedelman8 on this one.

**Comment by sheffner1226** [comment]
Any update on this?  Seems like it would be a good bug fix to implement.

**Comment by johnarnold** [comment]
@itdependsnetworks @jedelman8 ping

**Comment by jmcgill298** [comment]
#299 #300

**Pull request closed without merging**
