### PR TITLE
Modified cisco_ios_show_boot

### PR DESCRIPTION
**Pull request by shanecbauman**
##### ISSUE TYPE

 - New Template Pull Request

##### COMPONENT

**Template:** `ntc_templates/templates/cisco_ios_show_boot.textfsm`
**OS:** `cisco_ios`
**Command:** `show boot`

##### SUMMARY

Updated `show boot` template to include new formatting for Cisco IOS Gibraltar output.

Includes the old values and adds "Current Boot Variables", "Boot Mode", and "Switch Number"

**Before:**
```
BOOT path-list      : flash:c3750e-ipbasek9-mz.150-2.SE11.bin
Config file         : flash:/config.text
Private Config file : flash:/private-config.text
Enable Break        : yes
Manual Boot         : no
Allow Dev Key         : yes
HELPER path-list    : 
Auto upgrade        : yes
Auto upgrade path   :
NVRAM/Config file
      buffer size:   524288
Timeout for Config
          Download:    0 seconds
Config Download
       via DHCP:       disabled (next boot: disabled
```
**After:**
```
---------------------------
Switch 1
---------------------------
Current Boot Variables:
BOOT variable does not exist

Boot Variables on next reload:
BOOT variable = flash:packages.conf                                                                                                                                                                               
Manual Boot = no                                                                                                                                                                                                  
Enable Break = yes                                                                                                                                                                                                
Boot Mode = DEVICE                                                                                                                                                                                                
iPXE Timeout = 0
```

### CODE REVIEW

**Comment by jvanderaa** [comment]
Thanks @shanecbauman

**Comment by mayafox** [comment]
This is now causing tox to fail as the tests/cisco_ios/show_boot/cisco_ios_showboot.yml was not updated to reflect the new modified template.

**Comment by shanecbauman** [comment]
@mayafox thanks for the call out.  I requested a new [pull request](https://github.com/networktocode/ntc-templates/pull/1045) fixing the keys in the original yaml file.

**Comment by mayafox** [comment]
Np, was checking the status of my pull request and saw the merge checks where failing so poked around.

**Pull request merged**
