### PR TITLE
Added description in cisco_ios_show_ip_bgp_vpnv4_all_neighbors

### PR DESCRIPTION
**Pull request by 0lesen**
Added Description

### CODE REVIEW

**Comment by mjbear** [comment]
I have some suggestions I'll put forth, but that won't be until this evening.
Thank you. :slightly_smiling_face:

**Comment by mjbear** [comment]
@0lesen 
Please provide raw output (which contains a BGP peer Description) in your PR.
(Replace any potentially sensitive information with similar placeholders.)

With that raw output, use the [helper scripts to parse that raw output](https://github.com/networktocode/ntc-templates/blob/master/docs/dev/dev_parser.md#development-helper-scripts) and add that into your PR too.

https://github.com/networktocode/ntc-templates/blob/master/docs/dev/dev_environment.md

Ask if you have questions. Thank you.

I'd be glad to re-review once there's test data. :grin:

**Review by jmcgill298 — COMMENTED** [review]
Thanks for your PR @0lesen . As @mjbear requested, please update the test data to make this PR ready for review

**Comment by mjbear** [comment]
@0lesen
I submitted a PR (0lesen/ntc-templates/pull/1) against your patch.
This PR includes a few changes as well as test data (raw and structured yaml).

Thank you!

**Comment by mjbear** [comment]
Thank you @0lesen! :denmark:

If you have access to any different vpnv4 output please test against it and even include a sanitized example.

For example, I found that in the output I generated there was not a Local AS.

Let's make this template's test data fully cover any differences in the CLI output! :grinning:
Thank you!

**Review by jmcgill298 — APPROVED** [review]

**Pull request merged**
