### PR TITLE
Update for "cable type is ***" and "cisco version id is ***" in 'show interface transceiver' output

### PR DESCRIPTION
**Pull request by yevgeniy-voloshin**
Hi Team!
We have a lot of QSFP-40G-SR-BD by CISCO-AVAGO (part number is AFBR-79EBPZ-CS2) in N9K devices. For all of them 'show interface transceiver' output looks like:
```
Ethernet7/49
    transceiver is present
    type is QSFP-40G-SR-BD
    name is CISCO-AVAGO
    part number is AFBR-79EBPZ-CS2
    revision is 01
    serial number is AVM1828U4JD
    nominal bitrate is 20600 MBit/sec per channel
    Link length supported for 50/125um OM3 fiber is 100 m
    cisco id is 13
    cisco extended id number is 220
    cisco part number is 10-2945-02
    cisco product id is QSFP-40G-SR-BD
    cisco version id is V02
```

And current version of template have this error:
_**There was an error:  State Error raised. Rule Line: 23. Input Line:     cisco version id is V02**_

That's why I add line №23`'  ^\s+cisco\s+version\s+id'` to this template.
Please confirm my pull request, thanks in advance ;)

### CODE REVIEW

**Comment by yevgeniy-voloshin** [comment]
```
Ethernet7/49
    transceiver is present
    type is QSFP-40G-SR-BD
    name is CISCO-AVAGO
    part number is AFBR-79EBPZ-CS2
    revision is 01
    serial number is AVM1828U4JD
    nominal bitrate is 20600 MBit/sec per channel
    Link length supported for 50/125um OM3 fiber is 100 m
    cisco id is 13
    cisco extended id number is 220
    cisco part number is 10-2945-02
    cisco product id is QSFP-40G-SR-BD
    **cisco version id is V02**

```

**Comment by itdependsnetworks** [comment]
Please add to the tests to ensure there is no future regression

**Comment by yevgeniy-voloshin** [comment]
Dear Colleagues, @jvanderaa and @itdependsnetworks, I just added two new files **cisco_nxos_show_interface_transceiver2.raw** and **cisco_nxos_show_interface_transceiver2.yml** as you requested.

The **cisco_nxos_show_interface_transceiver2.raw** file contains full output of command "show interface transceiver" for all 60 interfaces from cisco Nexus9000 C93240YC-FX2 Chassis with NXOS: version 9.3(9).

This is second try of my first commit :)

**Comment by yevgeniy-voloshin** [comment]
Just added: 
  Create cisco_nxos_show_interface_transceiver2.raw
  #1337 opened Mar 26, 2023 by yevgeniy-voloshin
  Create cisco_nxos_show_interface_transceiver2.yml
  #1336 opened Mar 26, 2023 by yevgeniy-voloshin 
RAW and YAML for additional test (PR#1240)

**Review by yevgeniy-voloshin — COMMENTED** [review]
Additional tests cisco_nxos_show_interface_transceiver2.raw and  cisco_nxos_show_interface_transceiver2.yml for PR#1240

**Comment by ryanmerolle** [comment]
Can this be closed with #1365 merged?

**Comment by jmcgill298** [comment]
https://github.com/networktocode/ntc-templates/commit/b9272c760556679a6a59b124e95dc8918ab0d6ca

https://github.com/networktocode/ntc-templates/commit/44353baad2899ce489c1370150ecaba9460c351e

https://github.com/networktocode/ntc-templates/pull/953/files

**Pull request closed without merging**
